service:
  info: Account Microservice (Quality Assurance)
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rtr-ms-postgres:5432/db_account
    username: rtrpostgres
    password: pwd
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/rtr-ms
server:
  port: 16801
